# Generated by Django 4.1.7 on 2023-03-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='warrenty_claims',
            fields=[
                ('Ticket_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Middle_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField(unique=True)),
                ('Battery_brand', models.CharField(max_length=100)),
                ('Battery_type', models.CharField(max_length=100)),
                ('Battery_SerialNumber', models.CharField(max_length=100, unique=True)),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
    ]
